data:
  path: rhcore.data.data_modules.ddp_data_module
  name: DistTrainDistValidDataModule
  config:
    train_dataloader:
      dataset:
        path: 'rhcore.data.datasets.basic_image_dataset'
        name: 'BasicImageDataset'
        params:
          # max_dataset_size: 256
          folder_paths: $train_folder_paths
          data_prefix:
            gt: ''
            lq: ''
          pipeline:
            - type: LoadImageFromFile
              keys: [gt, lq]
            - type: Normalize
              keys: [gt, lq]
              mean: [0.5, 0.5, 0.5]
              std: [0.5, 0.5, 0.5]
      batch_size: $train_batch_size
      num_workers: $num_workers
      pin_memory: false
      persistent_workers: false
      sampler:
        type: DefaultSampler
        shuffle: true

    valid_dataloader:
      dataset:
        path: 'rhcore.data.datasets.basic_image_dataset'
        name: 'BasicImageDataset'
        params:
          folder_paths: $valid_folder_paths
          data_prefix:
            gt: ''
            lq: ''
          pipeline:
            - type: LoadImageFromFile
              keys: [gt, lq]
            - type: Normalize
              keys: [gt, lq]
              mean: [0.5, 0.5, 0.5]
              std: [0.5, 0.5, 0.5]
      batch_size: $valid_batch_size
      num_workers: $num_workers
      pin_memory: false
      persistent_workers: true
      sampler:
        type: DefaultSampler
        shuffle: true
