_import: "configs/base_data.yaml"

boat:
  path: 'rhopsr.boats.progressive_gausian_deblur_boat'
  name: 'ProgressiveGaussianDeblurRestorationBoat'

  models: $models

  upscale:
    path: 'torch.nn'
    name: 'Upsample'
    params:
      scale_factor: 8
      mode: 'bilinear'
      align_corners: false

  losses: 
    net:
      path: 'rhopsr.nn.losses.weighted_loss'
      name: 'WeightedLoss'
      params:
        base_loss_fn_str: mse
      wrapper: # This wrapper is more complex needs parameters
        mpath: 'rhopsr.nn.losses.wrappers.list_of_keys.ListOfKeys'
        params:
          keys: ["preds", "targets", "weights"]
          
  hyperparameters:
    curriculum:
      sigmas: [6.0, 3.0, 1.5, 0.75, 0.0]
      stage_kimgs: [200, 5000, 5000, 5000, 5000]
      fade_fraction: 0.5

optimization:
  net:
    path: 'torch.optim'
    name: 'Adam'
    params:
      lr: 0.0001
      betas: [0.9, 0.999]
      weight_decay: 0.0
    lr_scheduler: {}
  use_ema:
    ema_decay: 0.999
    ema_start: $ema_start

trainer:
  devices: $devices
  max_epochs: $max_epochs
  val_check_epochs: 1
  state_save_epochs: 1
  save_images: true

validation:
  save_images: true
  num_vis_samples: 4
  use_reference: true
  target_metric_name: psnr
  metrics:
    psnr:
      path: 'torchmetrics.image'
      name: 'PeakSignalNoiseRatio'
      wrapper: 'rhcore.metrics.wrappers.dict_2_params.Dict2ListParams'
      params:
        data_range: 2.0
    ssim:
      path: 'torchmetrics.image'
      name: 'StructuralSimilarityIndexMeasure'
      wrapper: 'rhcore.metrics.wrappers.dict_2_params.Dict2ListParams'
      params: {}

logging:
  root_dir: 'work_dirs'
  name: $experiment_name
  loggers:
    tensorboard:
      path: 'rhcore.loggers.tensorboard_logger'
      name: 'TensorBoardLogger'
      params:
        log_dir: 'work_dirs'
        name: $experiment_name

callbacks:
  - path: 'rhtrain.callbacks.state_cleaner'
    name: KeepTopKStateCallback
    params:
      top_k: 5

_vars:

  models:
    net:
      path: rhopsr.nn.multi_stage_vision_restormer
      name: MultiStageVisionRestormer
      params:
        base_config:
          path: rhopsr.nn.model_zoo.srcnn
          name: SRCNN
          params:
            in_channels: 6
            out_channels: 3
            base_channels: 64
        num_stages: 5

  max_epochs: 200

  devices: [4]

  train_batch_size: 256
  valid_batch_size: 32
  num_workers: 16

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_128
    lq: data/ffhq/ffhq_imgs/ffhq_32
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_128
    lq: data/celeba/subsets/celeba_32

  experiment_name: srcnn_pg_deblur_ffhq_128

  ema_start: 0