_import: configs/train_base_sr.yaml

_vars:

  models:
    net:
        path: 'cyclone.impl.hat.hat_arch'
        name: 'HAT'
        params: 
          scale: 8
          dim: 32
          depths: [3, 3, 3, 3]
          num_heads: 16
          window_size: 16

  losses: 
    net:
      path: 'rhopsr.nn.losses.weighted_loss'
      name: 'WeightedLoss'
      params:
        base_loss_fn_str: mse
      wrapper: # This wrapper is more complex needs parameters
        mpath: 'rhopsr.nn.losses.wrappers.list_of_keys.ListOfKeys'
        params:
          keys: ["preds", "targets", "weights"]

  max_epochs: 200

  devices: [0, 1, 2, 3, 4, 5]

  train_batch_size: 64
  valid_batch_size: 8
  num_workers: 16

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_256
    lq: data/ffhq/ffhq_imgs/ffhq_32
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_256
    lq: data/celeba/subsets/celeba_32

  experiment_name: cyclone_hat_ffhq_32_256

  ema_start: 0