_import: configs/base_image_config.yaml


boat:
  path: 'rhopsr.boats.base_restoration_boat'
  name: 'BaseRestorationBoat'

  models:
    net:
      path: 'rhopsr.nn.model_zoo.hat.hat_arch'
      name: 'HAT'
      params: 
        upscale: 8
        img_size: 64
        embed_dim: 96
        depths: [4, 4]
        num_heads: [6, 6]
        window_size: 16
        upsampler: 'pixelshuffle'

  losses: 
    net:
      path: 'rhopsr.nn.losses.haar_wavelet_loss'
      name: 'HaarWaveletLoss'
      params:
        level_weights: [1.0, 0.5, 0.3, 0.2]

visualization:
  save_images: true
  first_batch_only: true
  wnb: [0.5, 0.5]
  num_vis_samples: 4

_vars:

  max_epochs: 200

  norm_mean: [0.5, 0.5, 0.5]
  norm_std: [0.5, 0.5, 0.5]

  devices: [3]

  train_batch_size: 256
  valid_batch_size: 8
  num_workers: 32

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_256
    lq: data/ffhq/ffhq_imgs/ffhq_32
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_256
    lq: data/celeba/subsets/celeba_32

  experiment_name: baked_hat_ffhq_32_256

  ema_start: 0