_import: configs/base_image_config.yaml

boat:
  path: 'rhopsr.boats.adversarial_prior_restoration_boat'
  name: 'AdversarialPriorRestorationBoat'

  models:
    net:
      path: 'rhopsr.nn.model_zoo.hat.hat_models'
      name: 'HATModel'
      params: 
        model_name: 'HAT-Tiny'

    critic:
      path: 'rhopsr.nn.model_zoo.patchgan.patchgan_model'
      name: 'PatchGANDiscriminator'
      params:
        in_channels: 3
        base_channels: 64
        num_layers: 3
        norm: 'none'
        use_spectral_norm: True

  losses: 
    pixel_loss:
      path: 'torch.nn'
      name: 'L1Loss'
      params: {}

    lpips_loss:
      path: 'lpips'
      name: 'LPIPS'
      params:
        net: 'vgg'

    prior_loss:
      path: 'torch.nn'
      name: 'MSELoss'
      params: {}


    critic:
      path: 'rhopsr.nn.losses.hinge_gan_loss'
      name: 'HingeGANLoss'
      params: {}

optimization: 

  net:
    path: 'torch.optim'
    name: 'Adam'
    params:
      lr: 0.0001
      betas: [0.0, 0.99]
      weight_decay: 0.0
    lr_scheduler: {}
  
  critic:
    path: 'torch.optim'
    name: 'Adam'
    params:
      lr: 0.00005
      betas: [0.0, 0.99]
      weight_decay: 0.0
    lr_scheduler: {}

visualization:
  save_images: true
  first_batch_only: true
  wnb: [1.0, 0.0]
  num_vis_samples: 4

_vars:

  devices: [0]

  max_epochs: 600

  norm_mean: [0.0, 0.0, 0.0]
  norm_std: [1.0, 1.0, 1.0]
  inflate_factor: 10


  train_batch_size: 16
  valid_batch_size: 8
  num_workers: 32

  train_folder_paths:
    gt: data/df2k_download/datasets/DF2K/DF2K_train_HR
    lq: data/df2k_download/datasets/DF2K/DF2K_train_LR_bicubic/X4
    
  valid_folder_paths:
    gt: data/df2k_download/datasets/DIV2K/DIV2K_valid_HR
    lq: data/df2k_download/datasets/DIV2K/DIV2K_valid_LR_bicubic/X4

  experiment_name: hat_df2k_patchgan_sdxl_x4

  ema_start: 0